config/routes.rb
Rails.application.routes.draw do
    
  constraints subdomain: 'play' do
    root 'play#index', as: :play_root
    get '/tournaments/:tournament_id', to: 'play#show', as: :play_tournament
    get '/contestants/new', to: 'play/contestants#new', as: :play_new_contestant
    post '/contestants', to: 'play/contestants#create', as: :play_contestant
    post '/tournament', to: 'play#enter', as: :play_enter
  end

  resources :rounds
  # resources :contestants
  resources :games
  resources :tournaments
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  
    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
  
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :user

  validates :code, uniqueness: true

  after_initialize :set_code

  enum status:{
    waiting: 0,
    in_progress: 1,
    finished: 2
  }

  private

  def set_code
    self.code = generate_code #while Tournament.exists?(code: code)
  end

  def generate_code
    SecureRandom.alphanumeric(5)
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: %i[ show edit update destroy ]

  # GET /tournaments or /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1 or /tournaments/1.json
  def show
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments or /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to tournament_url(@tournament), notice: "Tournament was successfully created." }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1 or /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to tournament_url(@tournament), notice: "Tournament was successfully updated." }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1 or /tournaments/1.json
  def destroy
    @tournament.destroy!

    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: "Tournament was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tournament_params
      params.require(:tournament).permit(:name, :user_id)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_with(model: tournament) do |form| %>
  <% if tournament.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
        <% tournament.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tournaments/_tournament.html.erb
<div id="<%= dom_id tournament %>">
  <p>
    <strong>Name:</strong>
    <%= tournament.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= tournament.user_id %>
  </p>

</div>

app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render "form", tournament: @tournament %>

<br>

<div>
  <%= link_to "Show this tournament", @tournament %> |
  <%= link_to "Back to tournaments", tournaments_path %>
</div>

app/views/tournaments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tournaments</h1>

<div id="tournaments">
  <% @tournaments.each do |tournament| %>
    <%= render tournament %>
    <p>
      <%= link_to "Show this tournament", tournament %>
    </p>
  <% end %>
</div>

<%= link_to "New tournament", new_tournament_path %>

app/views/tournaments/new.html.erb
<h1>New tournament</h1>

<%= render "form", tournament: @tournament %>

<br>

<div>
  <%= link_to "Back to tournaments", tournaments_path %>
</div>

app/views/tournaments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tournament %>

<div>
  <%= link_to "Edit this tournament", edit_tournament_path(@tournament) %> |
  <%= link_to "Back to tournaments", tournaments_path %>

  <%= button_to "Destroy this tournament", @tournament, method: :delete %>
</div>